# Generated by Django 4.1.6 on 2023-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworkuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
