# Generated by Django 4.1.6 on 2023-02-11 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_socialnetworkuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quantity',
        ),
    ]
